# @name get-prompt
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="FelipeDeschamps.mp3"
Content-Type: audio/mpeg

< ./FelipeDeschamps.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/7f7d67d9-a3a2-480e-8783-e1c130d4fa6f/transcription
Content-Type: application/json

{
  "prompt": "item do artigo, conselho"
}